import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms and conditions for using CVCheck.',
}

export default function TermsPage() {
  return (
    <div style={{
      minHeight: '100vh',
      background: 'var(--bg)',
      color: 'var(--text-primary)',
      fontFamily: 'var(--font-sans)',
    }}>
      {/* Header */}
      <header style={{
        borderBottom: '1px solid var(--border)',
        padding: '0 24px',
        height: 58,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        maxWidth: 820,
        margin: '0 auto',
        width: '100%',
      }}>
        <Link href="/" style={{
          display: 'flex', alignItems: 'center', gap: 9,
          textDecoration: 'none', color: 'inherit',
        }}>
          <div style={{
            width: 32, height: 32, borderRadius: 9,
            background: 'var(--accent)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <svg width="16" height="16" fill="none" stroke="white" strokeWidth="2.2" viewBox="0 0 24 24">
              <path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/>
            </svg>
          </div>
          <span style={{ fontSize: 16, fontWeight: 700, letterSpacing: '-0.025em' }}>CVCheck</span>
        </Link>
        <Link href="/" style={{
          fontSize: 13, color: 'var(--text-secondary)',
          display: 'flex', alignItems: 'center', gap: 5,
          textDecoration: 'none',
        }}>
          <svg width="13" height="13" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
            <polyline points="15 18 9 12 15 6"/>
          </svg>
          Back to CVCheck
        </Link>
      </header>

      {/* Content */}
      <main style={{ maxWidth: 680, margin: '0 auto', padding: '56px 24px 96px' }}>
        <div style={{ marginBottom: 48 }}>
          <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.09em', textTransform: 'uppercase', color: 'var(--accent-text)', margin: '0 0 10px' }}>
            Legal
          </p>
          <h1 style={{ fontSize: 36, fontWeight: 700, letterSpacing: '-0.03em', margin: '0 0 12px', lineHeight: 1.1 }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 14, color: 'var(--text-tertiary)', margin: 0 }}>
            Last updated: May 2026
          </p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
          <Section title="What CVCheck is">
            <p>CVCheck is an AI-powered feedback tool that analyzes CVs, portfolios, and personal websites. We use Claude (by Anthropic) to read your content and generate a score, observations, and improvement suggestions.</p>
            <p>The feedback is generated by AI. It's designed to be useful and honest, but it's not a guarantee of employment outcomes. Different recruiters and companies look for different things — treat the feedback as one perspective, not gospel.</p>
          </Section>

          <Section title="Using CVCheck">
            <p>By using CVCheck, you agree to:</p>
            <ul>
              <li>Only submit content you own or have the right to share (your own CV, your own website, etc.).</li>
              <li>Not attempt to reverse-engineer, scrape, or abuse the service.</li>
              <li>Not use CVCheck for anything illegal or harmful.</li>
              <li>Not submit content that contains personal data of other people without their consent.</li>
            </ul>
            <p>We reserve the right to suspend access for anyone who misuses the service.</p>
          </Section>

          <Section title="Free scan">
            <p>Each person gets one free analysis — tracked by account or IP address. Creating multiple accounts to get more free scans is a violation of these terms. If you need more analyses, the Pro plan is €2 — that's genuinely the price we think is fair.</p>
          </Section>

          <Section title="Payments and refunds">
            <p><strong>Pro (€2 one-time):</strong> A single payment that unlocks the full analysis for one CV. This is not a subscription. Once you pay, you have permanent access to that analysis.</p>
            <p><strong>Premium (€7.99/month):</strong> A recurring subscription. You can cancel at any time from your account settings — your access continues until the end of the billing period.</p>
            <p><strong>Refunds:</strong> If you're not happy with your purchase, email us within 7 days and we'll refund you, no questions asked. After that, refunds are at our discretion.</p>
          </Section>

          <Section title="What we're responsible for">
            <p>We do our best to keep CVCheck reliable and useful. That said:</p>
            <ul>
              <li>We can't guarantee the AI feedback is always accurate or relevant to your specific industry or role.</li>
              <li>We're not liable for employment decisions made based on our feedback.</li>
              <li>We're not liable for downtime, data loss, or service interruptions, though we'll work hard to minimize them.</li>
            </ul>
            <p>CVCheck is provided "as is". We're a small team and we're honest about what we can and can't promise.</p>
          </Section>

          <Section title="Your content">
            <p>You own your CV and the content you submit. We don't claim any rights over it. By submitting content, you give us permission to process it through our systems (including Anthropic's API) for the purpose of generating your analysis.</p>
            <p>We don't use your CV content to train AI models or share it with third parties beyond what's needed to run the service.</p>
          </Section>

          <Section title="Account termination">
            <p>You can delete your account at any time from settings. When you do, we delete your personal data and analyses within 30 days.</p>
            <p>We can terminate accounts that violate these terms. If we do, we'll tell you why unless there's a legal reason we can't.</p>
          </Section>

          <Section title="Changes">
            <p>We may update these terms. If the changes are significant, we'll let you know by email. Continuing to use CVCheck after changes means you accept the new terms.</p>
          </Section>

          <Section title="Contact">
            <p>If you have questions about these terms, email <a href="mailto:hello@cvcheck.app" style={{ color: 'var(--accent-text)' }}>hello@cvcheck.app</a>.</p>
          </Section>
        </div>
      </main>

      <footer style={{
        borderTop: '1px solid var(--border)',
        padding: '20px 24px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        maxWidth: 820, margin: '0 auto', width: '100%',
        fontSize: 12, color: 'var(--text-tertiary)', flexWrap: 'wrap', gap: 10,
      }}>
        <span>© 2026 CVCheck</span>
        <div style={{ display: 'flex', gap: 16 }}>
          <Link href="/" style={{ color: 'var(--text-tertiary)', textDecoration: 'none' }}>Home</Link>
          <Link href="/privacy" style={{ color: 'var(--text-tertiary)', textDecoration: 'none' }}>Privacy</Link>
        </div>
      </footer>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
      <h2 style={{
        fontSize: 18, fontWeight: 700, letterSpacing: '-0.02em',
        color: 'var(--text-primary)', margin: 0,
        paddingBottom: 12, borderBottom: '1px solid var(--border)',
      }}>
        {title}
      </h2>
      <div style={{
        fontSize: 15, lineHeight: 1.75, color: 'var(--text-secondary)',
        display: 'flex', flexDirection: 'column', gap: 12,
      }}>
        {children}
      </div>
    </div>
  )
}
